name: CI/CD Pipeline

on:
  push:
    branches:
      - create-workflow
  pull_request:
    branches:
      - create-workflow
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Run tests
        run: go test ./...

  publish:
    runs-on: ubuntu-22.04
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          TAG=${GITHUB_REF##*/}
          docker build -t sergeysmagin95/12-sprint-workflow:${TAG} .

      - name: Push Docker image
        run: |
          TAG=${GITHUB_REF##*/}
          docker push sergeysmagin95/12-sprint-workflow:${TAG}
